# Site settings
baseURL = "https://yoga-orthez.fr"
languageCode = "fr-FR"
title = "Silvina Duhagon - Yoga Orthez"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "G-EJD2500NS7"

# Copyright
copyright = "&copy;2023 Silvina Duhagon"

[params]

  # Metadata for search engines and social sharing
  author = "Silvina Duhagon"
  description = "Silvina Duhagon - Yoga"
  shareImage = "images/share.png"
  twitterHandle = ""

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/sil-arbol.jpg"
      position = "center center"
      moreFiles = "'images/head-molino.jpeg', 'images/head-salleyoga.jpeg', 'images/head-yoga-utensilios.jpeg', 'images/head-salleyoga-2-b.jpg', 'images/sil-arbol.jpg'"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  #[[params.links]]
  #  [params.links.list1]
  #    heading = "Connect"
#
  #    [[params.links.list1.link]]
  #      text = "Blog"
  #      url = "#"
  #      new_tab = true # new tab
#
  #    [[params.links.list1.link]]
  #      text = "Email"
  #      url = "#"
  #      new_tab = false # Default, open at same tab
#
  #    [[params.links.list1.link]]
  #      text = "Newsletter"
  #      url = "#"
#
  ## Links List #2
  #[[params.links]]
  #  [params.links.list2]
  #    heading = "Social"
#
  #    [[params.links.list2.link]]
  #      text = "Twitter"
  #      url = "#"
#
  #    [[params.links.list2.link]]
  #      text = "Instagram"
  #      url = "#"
#
  #    [[params.links.list2.link]]
  #      text = "Dribbble"
  #      url = "#"
#
  ## Links List #3
  #[[params.links]]
  #  [params.links.list3]
  #    heading = "Network"
#
  #    [[params.links.list3.link]]
  #      text = "Link One"
  #      url = "#"
#
  #    [[params.links.list3.link]]
  #      text = "Link Two"
  #      url = "#"
#
  #    [[params.links.list3.link]]
  #      text = "Link Three"
  #      url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
